import Footer from '@/components/Footer';
import Header from '@/components/Header';
import Navbar from '@/components/Navbar';
import SearchBox from '@/components/SearchBox';
import './globals.css';
import Providers from './Providers';

export const metadata = {
  title: 'IMbd',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {/* {header} */}
          <Header />

          {/* {navbar} */}
          <Navbar />

          {/* {searcbar} */}
          <SearchBox />

          {children}

          <Footer />
        </Providers>
      </body>
    </html>
  );
}
